-- MySQL Script generated by MySQL Workbench
-- Tue Jul  5 21:34:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema orientacaobd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema orientacaobd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `orientacaobd` DEFAULT CHARACTER SET utf8 ;
USE `orientacaobd` ;

-- -----------------------------------------------------
-- Table `orientacaobd`.`orientacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orientacaobd`.`orientacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `palavrachave` VARCHAR(255) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `texto` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT current_timestamp() on update current_timestamp(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
